---

# see https://terraform-docs.io/user-guide/configuration/formatter/
formatter: "markdown table"

# see https://terraform-docs.io/user-guide/configuration/output/
output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

# see https://terraform-docs.io/user-guide/configuration/settings/
settings:
  anchor: false
  color: true
  default: true
  escape: false
  indent: 3
  required: true
  sensitive: true
  type: true

# see https://terraform-docs.io/user-guide/configuration/sort/
sort:
  enabled: true
  by: required

# see https://terraform-docs.io/user-guide/configuration/sections/
sections:
  show:
    - inputs
    - outputs

# see https://terraform-docs.io/user-guide/configuration/version/
version: ">= 0.16.0, < 1.0.0"
