---

name: Repository Management

on:
  pull_request:

jobs:
  assign-pr-to-author:
    runs-on: ubuntu-latest
    name: assign-pr-to-author

    steps:
      - name: Assign Pull Request to Author
        uses: technote-space/assign-author@v1
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
