---
name: "Documentation: terraform-docs"

on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        examples:
          - "./examples/basic"

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render documentation for Module and push changes back to branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: inject
          git-push: true
          working-dir: "./"

      - name: Render documentation for Examples and push changes back to branch
        uses: terraform-docs/gh-actions@v1.0.0
        with:
          config-file: "../../.terraform-docs.yml"
          output-file: "README.md"
          output-method: inject
          git-push: true
          working-dir: "${{ matrix.examples }}"
