---
name: "Documentation: terraform-docs"

on:
  push:

jobs:
  docs:
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        examples:
          - "./examples/basic"
          - "./examples/branch_protection"
          - "./examples/complex"
          - "./examples/deploy_keys"
          - "./examples/files"
          - "./examples/issue_labels"
          - "./examples/pages"
          - "./examples/template"
          - "./examples/webhook"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render documentation for Module and push changes back to branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: ".terraform-docs.yml"
          output-file: "README.md"
          output-method: inject
          git-push: true
          working-dir: "./"

      # see https://github.com/terraform-docs/gh-actions/releases
      - name: Render documentation for Examples and push changes back to branch
        uses: terraform-docs/gh-actions@v1.3.0
        with:
          config-file: "../../.terraform-docs.yml"
          output-file: "README.md"
          output-method: inject
          git-push: true
          working-dir: "${{ matrix.examples }}"
